# Site settings
title: Franklin Antony
description: Web Developer and an Aspiring Engineer.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Franklin Antony
user_description: 
user_title: Web Developer and an Aspiring Engineer
email: franklinanton.007@gmail.com
twitter_username: franklinrockz
github_username:  franklinrockz
gplus_username:  l

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
