# Site settings
title: Franklin Anotny
description: Web Developer and an Aspiring Engineer from India.
baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Franklin Antony
user_description: Web Developer and an Aspiring Engineer.
user_title: Web Developer
email: franklinanton.007@gmail.com
twitter_username: beingfranklin
github_username:  beingfranklin
gplus_username:  

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
